---
title: Evolucijska utrka: suradnja, obmana i kognitivni razvoj
---
%%{init: {'themeVariables': {'fontSize': '17px'}, 'flowchart': {'nodeSpacing': 38, 'rankSpacing': 52}}}%%
flowchart TD
A[Suradnička komunikacija] --> B[Mogućnost obmane]
A --> C[Zajednička intencionalnost]
B --> D[Strategije zavaravanja]
B --> E[Mehanizmi detekcije]
D --> F[Evolucijski pritisak]
E --> F
C --> F
F --> G[Gramatički ustrojen simbolički sustav]
