---
title: Masovna komunikacija i kultura
---
flowchart TD
A[Masovni mediji] --> B[Kulturna homogenizacija]
A --> C[Globalni kulturni obrasci]
B --> D[Gubitak raznolikosti]
C --> E[Medijski i idejni krajolici]
E --> F[Hibridizacija globalnog i lokalnog]
