---
title: Ciklus nadzornog kapitalizma
---
flowchart LR
A[Aktivnost] -->|stvara| B[Podaci]
B -->|omogućuju| C[Predviđanje]
C --> D[Prediktivni proizvodi]
C --> E[Ciljanje]
D --> F[Profit]
E --> F
E -->|povrat| A
