---
title: Evolucijski tijek društvenih mreža
---
flowchart TD
A[SixDegrees 1997] --> B[MySpace, Facebook 2004]
B --> C[Twitter, Instagram]
C --> D[Platforme za kratki video TikTok]
D --> E[Algoritamsko posredovanje]
E --> F[Javni diskurs, aktivizam, dezinformacije]
