%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[Televizija] --> B[Vizualnost]
    A --> C[Istodobnost]
    B --> D[Zajedničke slike]
    C --> E[Kolektivno iskustvo]
    D --> F[Zajednička imaginacija]
    E --> F
    F --> G[Kohezija zajednice]
