---
title: Intelektualni temelji informacijskog društva
---
%%{init: {'themeVariables': {'fontSize': '18px'}, 'flowchart': {'nodeSpacing': 38, 'rankSpacing': 52}}}%%
flowchart TD
A[Vannevar Bush: Memex] --> B[Asocijativno indeksiranje]
B --> C[Preteča hiperteksta i WWW]
D[Norbert Wiener: Kibernetika] --> E[Povratna sprega i samoregulacija]
E --> F[Temelj za AI, mreže i autonomne sustave]
