---
title: 1866. – Transatlantski telegrafski kabel
---
flowchart TD
A[Pothvat usporediv s kasnijim svemirskim istraživanjima] --> B[Trijumf ljudske upornosti i inženjerske vještine]
B --> C[Jedinstven informacijski prostor]
C --> D[Stari i Novi svijet povezani]
D --> E[Temelj za buduće elektroničke mreže]
