---
title: Tiskarski stroj kao agent promjene
---
flowchart TD
A[Tiskarski stroj Gutenberg, o. 1440.] --> B[Naglašavanje vizualnog nad auditivnim]
B --> C[Linearno, sekvencijalno mišljenje]
C --> D[Analitički način obrade informacija]
D --> E[Gutenbergova galaksija McLuhan, 1962]
