---
title: Temeljni elementi suradnje u multiagentskim sustavima
---
flowchart LR
A[Zajednički cilj] --> B[Razmjena]
B --> C[Pregovaranje]
B --> D[Kolaborativni alati]
C --> E[Rješavanje sukoba]
D --> F[Povjerenje i koherentnost]
E --> F
