---
title: 19. stoljeće – početak elektroničke komunikacije
---
flowchart TD
A[Prijenos poruka brzinom većom od fizičkog vozila] --> B[Telegraf]
B --> C[Telefon]
C --> D[Elektronička komunikacija]
D --> E[Kvalitativna promjena u društvenoj organizaciji]
