---
title: Internetska javna sfera
---
flowchart TD
A[Javna sfera] --> B[Fragmentirani prostor]
B --> C[Komore jeke]
B --> D[Filtarski mjehurići]
C --> E[Polarizacija]
D --> E
E --> F[Otežano razumijevanje]
