---
title: Internetska javna sfera
---
flowchart TD
A[Habermas: jedinstvena javna sfera] --> B[Digitalni prostor fragmentiran]
B --> C[Komore jeke]
B --> D[Filtarski mjehurići]
C --> E[Polarizacija]
D --> E
E --> F[Otežano međusobno razumijevanje]
