---
title: Cijena sveopće povezanosti
---
flowchart TD
A[Društvena i politička razina] --> B[Osobna, psihološka razina]
B --> C[Socijalna usporedba na mrežama]
C --> D[Tjeskoba, osjećaj neadekvatnosti]
D --> E[Zamagljivanje granica: rad / odmor]
E --> F[Pritisak stalne dostupnosti]
