---
title: Dijalektika globalne i lokalne kulture
---
flowchart TD
A[Globalna integracija] --> B[Unificiranje kulturnih praksi]
A --> C[Lokalna posebnost]
B --> D[Napetost]
C --> D
D --> E[Kulturni krajolik 21. st.]
