---
title: Utjecaj telefona
---
flowchart TD
A[Telefon] --> B[Ukidanje nužnosti fizičke prisutnosti]
B --> C[Intimna komunikacija na daljinu]
C --> D[Privatna i javna sfera]
D --> E[Nova dijalektika: bliskost i ugrožena privatnost]
E --> F[Glas kao nositelj identiteta i emocija]
