---
title: Kognitivni proces agenta
---
flowchart TD
A[Percepcija stvarnosti] --> B[Simbolička reprezentacija]
B --> C[Jezična struktura, gramatika i pravila]
C --> D[Mentalna mapa, unutarnji model svijeta]
D --> E[Odlučivanje i djelovanje]
E -->|Povratna sprega| A
