---
title: Osobne kompetencije
---
flowchart TD
        A[Samosvijest: prepoznavanje vlastitih osjećaja i utjecaja] --> B[Samoregulacija: upravljanje unutarnjim stanjima i impulsima]
        B --> C[Motivacija: unutarnji poriv za postignućem i ustrajnost]
        D[Empatija: prepoznavanje i suosjećanje s emocijama drugih]
        E[Društvene vještine: upravljanje odnosima, uvjeravanje, vođenje]
    C -->|prijelaz iz unutarnjeg u međuljudsko| D
    D --> E
