---
title: Faza 1
---
flowchart TD
        A[Agent za uski zadatak: duboka, ali izolirana inteligencija]
        B[Agent s alatima: koristi vanjske resurse, API-je, baze]
        C[Višeagentski sustav: komunikacija, pregovaranje, suradnja]
        D[Digitalni kolektiv: emergentna svojstva, kolektivno pamćenje, samoorganizacija]
    A -->|Nadilaženje izolacije| B
    B -->|Društvenost| C
    C -->|Prelazak u kvalitetu| D
