%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart LR
    A[Klijent] --> B[API sloj]
    B --> C[Poslužitelj]
    C --> D[Odgovor]
    D --> B
    B --> A
