%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[Agent bez alata] --> B[Ograničen prostor]
    C[API baze pretraga alati] --> D[Integracija alata]
    A --> D
    D --> E[Proširen prostor]
    E --> F[Veća djelotvornost]
