%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[API poziv] --> B[Metoda]
    A --> C[URL i parametri]
    A --> D[Zaglavlja]
    A --> E[Tijelo]
