%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[LLM agenti] --> B[Zdravstvo]
    A --> C[Poslovanje]
    A --> D[Kreativne industrije]
    B --> B1[Dijagnoze]
    B --> B2[Terapije]
    C --> C1[Podrška]
    C --> C2[Opskrba]
    D --> D1[Ideje]
    D --> D2[Dizajn]
