%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[Korisnički signali] --> B[Profil korisnika]
    B --> C[Algoritmi preporuke]
    C --> D[Personalizirani sadržaj]
    D --> E[Reakcija korisnika]
    E --> A
