%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[Automatizirana rutina] -->|Neočekivani događaj| B[Prekid automatizma]
    B --> C[Ljudska intervencija]
    C --> D[Prilagodba i učenje]
    D --> E[Novo stanje]
    E -->|Povratak ili nova norma| A
