%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[Korisnički profil] --> B[Tempo]
    B --> C[Analiza sna]
    B --> D[Ambijent]
    B --> E[Jutarnje informacije]
    C --> F[Optimalno buđenje]
    D --> F
    E --> F
    F --> G[Informiran i odmoren korisnik]
