%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[Prag za redizajn] --> B[Samopoboljšanje]
    B --> C[Nova generacija AI]
    C --> D[Veća sposobnost]
    D --> E[Daljnje poboljšanje]
    E --> F[Superinteligencija]
