%%{init: {'themeVariables': {'fontSize': '16px'}, 'flowchart': {'nodeSpacing': 35, 'rankSpacing': 40}}}%%
flowchart TD
    A[Čovjek] --> C[Zajednički rad]
    B[AI agent] --> C
    C --> D[Zajednička odluka]
    D --> E[Povratna veza]
    E --> F[Uzajamno učenje]
    F --> A
    F --> B
