graph TD
subgraph "Tehnološki proces"
direction TB
Agent -->|Prepoznaje| Problem
Problem -->|Zahtijeva| Svrha[Ispunjavanje svrhe]
Agent -->|Koristi i stvara| Tehnologija
Tehnologija -->|Omogućuje| Svrha
Svrha -->|Usmjerava djelovanje| Agent