graph TD
A["Tisak s pomičnim slovima (Gutenberg)"] --> B[Masovna proizvodnja i dostupnost knjiga]
B --> C["Demokratizacija znanja i masovno širenje ideja"]
B --> D["Standardizacija jezika"]
C --> E["Širenje znanstvenih radova (Kopernik, Newton) i vje...]
C --> F["Pojava novih formi: novine i romani"]