%%{init: {'theme': 'base', 'themeVariables': { 'background': '#ffffff'}}}%%
graph TD
subgraph "Proces demokratizacije znanja putem tiska"
direction TB
direction LR
A[Razvoj tiskarstva] --> B[Smanjenje troškova i vremena proizvodnje]
B --> C[Masovna dostupnost tiskanih tekstova]
C --> D[Brža razmjena, provjera i nadopuna ideja]
C --> E[Transformacija sveučilišta]
D --> F[Stvaranje isprepletene znanstvene mreže]
E --> G[Uspostava arhiva, knjižnica i znanstvenih časopisa]
F & G --> H[Demokratizacija znanja]