---
title: Transformacija komunikacije u političkoj sferi
---
flowchart TD
A[Jednosmjerni kanal] --> B[Dvosmjerna komunikacija]
B --> C[Višesmjerna interakcija]
B --> D[Javna mreža]
C --> E[Interaktivna javna sfera]
D --> E
