---
title: Funkcije usmene predaje
---
flowchart TD
A[Usmene predaje] --> B[Prijenos znanja i pamcenja]
A --> C[Drustvena integracija i identitet]
A --> D[Legitimacija poretka i kontrola]
A --> E[Estetska i zabavna funkcija]
