%%{init: {'theme': 'base', 'themeVariables': { 'background': '#ffffff'}}}%%
graph TD
A[Prva revolucija Usmenost] --> B[Druga revolucija Pismo]
B --> C[Treća revolucija Tisak]
C --> D[Četvrta revolucija Digitalno doba]