graph TD
A[Izum tiskarskog stroja Johannes Gutenberg, o. 1440.] --> B[Masovna proizvodnja pisanih materijala]
B --> C[Povećana dostupnost i niža cijena knjiga]
C --> D[Širenje pismenosti i ideja Humanizam, Renesansa, Ref...]
D --> E[Standardizacija jezika i stvaranje nacionalnih kultura]
D --> F[Nastanak javne sfere i javnog mnijenja]