graph TD
subgraph 7.2.4 Transverzalna Primjena
A[AI Algoritmi za Personalizaciju] --> B[Elektronička Trgovina]
A --> C[Medijski Sadržaji]
A --> D[Informiranje i Vijesti]
A --> E[Obrazovanje]
A --> F[Zdravstvena Skrb]