graph TD
subgraph "Razina integracije djelovanja"
direction TB
direction LR
A[Koordinacija Usklađivanje radi izbjegavanja sukoba] --> B[Kooperacija Podjela rada i resursa]
B --> C[Suradnja (Kolaboracija) Zajedničko stvaranje i dijel...]
end