graph TD
subgraph Aplikacijsko Programsko Sučelje (API) kao most
A[Aplikacija A Korisnik usluge]
B[Aplikacija B / Usluga Pružatelj usluge]
A -->|API Poziv (Zahtjev)| B
B -->|API Odgovor (Podaci/Funkcija)| A