graph TD
subgraph "Načelo efikasnosti u praksi"
direction TB
Optimalnost[Težnja optimalnom rješenju] --> Kompromis
Resursi[Ograničeni resursi Vrijeme, energija, računanje] --> Kompromis
Kompromis[Kompromis: 'Dovoljno dobro' rješenje] --> Efikasnost[Efikasno djelovanje]