graph TD
subgraph "Proces generalizacije u LLM-u"
direction TB
direction LR
A[Golemi i raznolik skup podataka za učenje] --> B[Veliki jezični model]
B -->|Uspješno rješava| C[Zadatci unutar distribucije (I.D.) Podaci slični oni...]
B -->|Izazov u rješavanju| D[Zadatci izvan distribucije (O.O.D.) Podaci bitno raz...]
end