%%{init: {'theme': 'base', 'themeVariables': { 'background': '#ffffff'}}}%%
graph TD
A["Misaoni proces Odabran je najpovoljniji jutarnji le...] --> B
B[Akcija Poziv sučelju: <code>pretraga_hotela_api</cod...] --> C
C[Opažaj Sustav je zaprimio popis hotela s pripadajući...]