graph TD
subgraph "Evolucijski tijek drustvenih mreza"
direction TB
A[SixDegrees 1997] --> B[Friendster 2002]
B --> C[Facebook 2004]
C --> D[Twitter 2006]
D --> E[Instagram 2010]
E --> F[TikTok 2016]
end
