graph TD
subgraph "Paradigme istraživanja"
direction TB
Simbolicki[Simbolički pristup (GOFAI)]
Konekcionisticki[Konekcionistički pristup (Neuronske mreže)]
Hibridni[Hibridni pristup (Sinteza simboličkog i konekcionist...]
Razvojni[Razvojni pristup (Utjelovljena kognicija)]
end
Simbolicki --> AGI[Umjetna opća inteligencija (AGI)]
Konekcionisticki --> AGI
Hibridni --> AGI
Razvojni --> AGI