---
title: Uloge pismenosti
---
flowchart TD
A[Pismenost] --> B[Pristup složenim sustavima znanja]
A --> C[Kognitivna preobrazba<br>apstraktno mišljenje]
A --> D[Društvena preobrazba<br>mobilnost, emancipacija]
B --> E[Osnažen agent]
C --> E
D --> E
