---
title: Uloge pismenosti
---
%%{init: {
  "themeVariables": { "fontSize": "20px" },
  "flowchart": { "htmlLabels": false, "nodeSpacing": 40, "rankSpacing": 60 }
}}%%
flowchart TD
A[Pismenost] --> B[Pristup složenim<br/>sustavima znanja]
A --> C[Kognitivna preobrazba<br/>apstraktno mišljenje]
A --> D[Društvena preobrazba<br/>mobilnost i emancipacija]
B --> E[Osnažen<br/>agent]
C --> E
D --> E
