%%{init: {'theme': 'base', 'themeVariables': { 'background': '#ffffff'}}}%%
graph TD
A[Pismo] --> B[Tiskarski stroj]
B --> C[Telegraf]
C --> D[Telefon]
D --> E[Radio i Televizija]
E --> F[Internet]
F --> G[Web 2.0 / Društveni mediji]
G --> H[AI posredovani agenti]
subgraph "Preddigitalno doba"
direction TB
A
B
C
D
E
end
subgraph "Digitalno doba"
direction TB
F
G
H
end