flowchart TD
A["Komunikacija primata<br>ograničena na<br>neposredne potrebe"] --> B["Prijelazni stupanj<br>gesta i pantomima<br>ikoničko prikazivanje"]
B --> C["Konvencionalizirani jezik<br>arbitrarni znakovi<br>i gramatika"]
C --> D["Složena ljudska<br>komunikacija<br>apstrakcija i kreativnost"]
