graph TD
%%{init: {'theme': 'base', 'themeVariables': { 'background': '#ffffff'}}}%%
subgraph Razvoj rane elektroničke komunikacije
A[1837. – Komercijalni telegraf (Cooke i Wheatstone u...] --> B[1844. – Prva službena Morseova poruka ("What hath Go...]
B --> C[1866. – Uspješno položen trajni transatlantski teleg...]
C --> D[1876. – Alexander Graham Bell patentira telefon]
D --> E[1878. – Otvorena prva komercijalna telefonska centrala]