flowchart TD
A[Inovacija] --> B[Društvena elita]
B -->|Usklađenost s interesima korist, status, moć| C[Prihvaćanje i ubrzano širenje]
B -->|Prijetnja poretku narušavanje statusa quo| D[Odbacivanje, ograničavanje i usporavanje širenja]
