%%{init: {'themeVariables': {'fontSize': '18px'}, 'flowchart': {'nodeSpacing': 40, 'rankSpacing': 54}}}%%
flowchart TD
A[Inovacija] --> B[Društvena elita]
B --> C[Usklađenost s interesima]
B --> D[Prijetnja poretku]
C --> E[Prihvaćanje i ubrzano širenje]
D --> F[Odbacivanje i usporavanje]
