graph TD
subgraph "Temeljni pokretači preoblikovanja društvene dinamike"
direction TB
A[Obrada informacija] --> B[Novi znanstveni i poslovni uvidi]
C[Automatizacija kognicije] --> D[Promjena paradigme rada]
E[Novi oblici interakcije] --> F[Pitanja povjerenja i prilagodbe]
G[Koncentracija tehnologije] --> H[Novi centri moći i nadzora]
end