graph TD
subgraph "Preobrazba društvene memorije pojavom pisma"
direction TB
A[Usmena kultura: fluidno i ograničeno znanje] --> B[Pismo: Tehnologija zapisa]
B --> C[Eksternalizacija znanja: pohrana izvan ljudskog uma]
C --> D[Složeno društvo]
C --> E[Država i birokracija]
C --> F[Znanost i povijest]
C --> G[Trajna i kumulativna kulturna baština]
end