graph TD
subgraph Ciklus nadzornog kapitalizma
direction LR
A[Korisnička aktivnost (ponašanje na mreži)] --> B[Prikupljanje podataka (bihevioralni višak)]
B --> C[Analiza i predviđanje (strojno učenje)]
C --> D[Prediktivni proizvodi (bihevioralne budućnosti)]
D --> E[Ciljanje i manipulacija (modifikacija ponašanja)]
E --> F[Ostvarivanje profita]
E --> A
end