graph TD
subgraph "Proces civilizacijskog razvoja"
direction TB
direction LR
A[Iskustvo i spoznaja] --> B[Pohrana znanja]
B --> C[Agent prijenosa]
C --> D[Kumulacija i nadogradnja]
D --> E[Složeni društveni sustavi]
E --> F[Razvoj civilizacije]
end