---
title: Put znanja od ograničenog pristupa do šire dostupnosti
---
flowchart TD
A[Rukopisna kultura<br>ograničen pristup] --> B[Tiskarska revolucija<br>masovna proizvodnja]
B --> C[Kultura citanja<br>široka pismenost]
C --> D[Digitalno doba<br>univerzalan pristup]
