graph TD
subgraph "Proces kulturnog širenja"
direction TB
direction LR
A[Izvorna kultura] --> B[Kulturni proizvod (glazba, film, anime)]
B --> C[Digitalne platforme Internet, društvene mreže]
C --> D[Globalna publika]
D --> E[Kulturni utjecaj]
E --> F[Hibridizacija i lokalna prilagodba]
E --> G[Meka moć (Soft Power)]
end