---
title: Od reformacije do znanstvene revolucije
---
%%{init: {'themeVariables': {'fontSize': '19px'}, 'flowchart': {'nodeSpacing': 34, 'rankSpacing': 56}}}%%
flowchart TD
I[Tiskarski stroj] --> A[Reformacija]
A --> B[Pad autoriteta]
A --> C[Osobna spoznaja]
A --> D[Radna etika]
B --> E[Znanstvena metoda]
C --> F[Samostalni istraživač]
D --> G[Racionalna disciplina]
E --> H[Znanstvena revolucija]
F --> H
G --> H
