graph TD
subgraph "Razvojni put djelatne moći"
direction TB
direction LR
A[Evolucijski preduvjet: Dvonožnost] --> B[Anatomska posljedica: Oslobođene ruke i opozicijski...]
B --> C[Tehnički čin: Izrada i uporaba oruđa]
C --> D[Kognitivna integracija: Proširenje tjelesne sheme]
D --> E[Ontološka posljedica: Iskorak u moći i preobrazba ag...]
end