graph TD
subgraph "Geneza Ambijentalne Inteligencije"
direction TB
A[Sveprisutno Računarstvo (M. Weiser, 1991) Tehnologij...] -->|Stapanje dviju paradigmi| C[Ambijentalna Inteligencija (AmI)]
B[Distribuirana Umjetna Inteligencija (Sustavi s više...] -->|Stapanje dviju paradigmi| C
C -->|Rezultira| D[Okruženje koje je: - Osjetljivo (perceptivno) - Pril...]
end