graph TD
subgraph "Pokretači transformacije"
direction TB
A[Digitalizacija]
B[Globalno umrežavanje]
C[Umjetna inteligencija]
end
subgraph "Nove komunikacijske paradigme"
direction TB
D[Automatizacija]
E[Personalizacija]
F[Interaktivnost i datafikacija]
end
subgraph "Područja primjene i utjecaja"
direction TB
G[Gospodarstvo]
H[Obrazovanje]
I[Javna sfera i politika]
J[Osobni život i kultura]
end
A --> D
B --> F
C --> D
C --> E
D & E & F --> G
D & E & F --> H
D & E & F --> I
D & E & F --> J