graph TD
subgraph "Procesi potaknuti masovnom komunikacijom"
direction TB
A[Masovni mediji: Globalni doseg] --> B[Prijenos kulturnih sadržaja]
B -->|Jednosmjerno širenje dominantnih obrazaca| C[Kulturna homogenizacija Gubitak raznolikosti, standa...]
B -->|Interakcija s lokalnim kontekstom| D[Kulturna hibridizacija / Glokalizacija Stvaranje nov...]
end