---
title: Put znanja od ograničenog pristupa do šire dostupnosti
---
flowchart TD
A[Ograničen pristup] --> B[Tisak]
B --> C[Šira pismenost]
B --> D[Veća dostupnost]
C --> E[Demokratizacija znanja]
D --> E
