graph TD
subgraph Životni ciklus modela
direction LR
A[1. Definiranje problema] --> B[2. Prikupljanje i priprema podataka]
B --> C[3. Razvoj i treniranje modela]
C --> D[4. Vrednovanje modela]
D --> E[5. Implementacija]
E --> F[6. Nadzor i održavanje]
F -->|Povratna veza| B
end