graph TD
subgraph Shematski prikaz komunikacijskih revolucija
direction LR
A[Revolucija Pisma cca 3500. pr. Kr.] --> B[Ključna tehnologija: Fonetski alfabet]
B --> C[Temeljni učinak: Pohrana znanja izvan pamćenja, nast...]
C --> D[Revolucija Tiska cca 1450. g.]
D --> E[Ključna tehnologija: Tiskarski stroj]
E --> F[Temeljni učinak: Masovna distribucija znanja, reform...]
F --> G[Revolucija Elektroničkih medija 19. i 20. st.]
G --> H[Ključna tehnologija: Telegraf, radio, TV]
H --> I[Temeljni učinak: Poništavanje prostora i vremena, "g...]
I --> J[Revolucija Digitalnih medija kraj 20. st.]
J --> K[Ključna tehnologija: Internet, računalo, mobilne teh...]
K --> L[Temeljni učinak: Globalna umreženost, interaktivnost...]
end