---
title: Ciklus algoritamske pristranosti
---
flowchart TD
A[Pristrani povijesni podatci] --> B[Algoritam uči obrasce]
B --> C[Generiranje pristranih odluka/predviđanja]
C --> D[Društveni ishodi pojačavaju nejednakost]
D --> E[Stvaranje novih pristranih podataka]
E --> A
