---
title: Razvoj rane elektroničke komunikacije
---
flowchart TD
A["1837. Komercijalni<br>telegraf: Cooke i<br>Wheatstone, UK"] --> B["1844. Prva službena<br>Morseova poruka<br>What hath God wrought"]
B --> C["1866. Trajni<br>transatlantski<br>telegrafski kabel"]
C --> D["1876. Alexander<br>Graham Bell patentira<br>telefon"]
D --> E["1878. Prva komercijalna<br>telefonska centrala"]
