graph TD
subgraph Standardna uputa
direction LR
A[ULAZ: Pitanje: U kafeteriji je bilo 23 jabuke. Ako s...] --> B[IZLAZ (Vjerojatno pogrešan): 29]
end
subgraph Uputa s lancem misli
direction LR
C[ULAZ: Pitanje: U kafeteriji je bilo 23 jabuke. Ako s...] --> D["IZLAZ (Vjerojatno ispravan): Naravno, razmislimo ko...]
end