---
title: Buduci vektori i izazovi
---
flowchart TD
A[Govor] --> B[Pismo]
B --> C[Tisak]
C --> D[Digitalno doba]
D --> E[AI posredovana komunikacija]
D --> F[Imersivna stvarnost - VR i AR]
D --> G[Internet stvari - IoT]
E --> H[Buducnost civilizacije?]
F --> H
G --> H
