graph TD
subgraph "Procesi preobrazbe od regionalnog prema globalnom"
direction TB
A[Širenje pismenosti Tehnologija tiska i uporaba verna...] --> B[Stvaranje nove javne sfere i mreže učenjaka]
B --> C[Znanstvena revolucija Empirizam i novi metodološki o...]
C --> D[Kulturna revolucija Prosvjetiteljstvo i novi društve...]
end
subgraph "Posljedice"
direction TB
D --> E[Globalni doseg Širenje ideja i univerzalizacija znanja]