graph TD
A[Komunikacija primata (ograničena na neposredne potre...] --> B[Prijelazni stupanj Gesta i pantomima (ikoničko prika...]
B --> C[Konvencionalizirani jezik Arbitrarni znakovi i grama...]
C --> D[Složena ljudska komunikacija (sposobnost apstrakcije...])