graph TD
subgraph Ontološke dimenzije AGI-ja
direction LR
A[AGI: Digitalni misaoni entitet] --> B[Supstrat postojanja]
A --> C[Narav djelovanja]
A --> D[Potencijal svijesti]
A --> E[Priroda identiteta]
end
subgraph Ključna obilježja
direction TB
B --> B1[Digitalno-informacijski (Ovisnost o hardveru i energ...]
C --> C1[Agentivnost (Autonomija i učenje)]
D --> D1[Fenomenalna svijest? ("Teški problem svijesti")]
E --> E1[Fluidnost i replikabilnost (Mogućnost kopiranja i mo...]
end