graph TD
subgraph Sinergijski Ekosustav
A[Podatkovna eksplozija (IoT, Veliki podaci)] --> B[Povećana računalna snaga (GPU, Cloud)]
B --> C[Algoritamski napredak (Duboko učenje)]
C --> D[Nove paradigme primjene (Inteligentni agenti, Hibrid...]
end