graph TD
subgraph Sustav resursa
direction LR
A[Agenti <br><i>(npr. ribari, šumari)</i>] -- Odluke o djelovanju --> F
S1(Zaliha <br><i>(npr. količina drvne mase)</i>) -- Stanje utječe na odluke --> A
F{Tokovi <br><i>(ulazni/izlazni)</i>}
S1 -- Izlazni tok --> F
F -- Ulazni tok --> S1
end
style A fill:#cde4ff,stroke:#333,stroke-width:2px
style S1 fill:#e6ffcc,stroke:#333,stroke-width:2px
style F fill:#fff2cc,stroke:#333,stroke-width:2px