graph TD
style Optimalnost fill:#f9f9f9,stroke:#333,stroke-width:2px
style Resursi fill:#f9f9f9,stroke:#333,stroke-width:2px
style Kompromis fill:#e6f3ff,stroke:#005c99,stroke-width:2px
style Efikasnost fill:#d5f5e3,stroke:#27ae60,stroke-width:2px
subgraph "Načelo efikasnosti u praksi"
Optimalnost(Težnja optimalnom rješenju) --> Kompromis
Resursi(Ograničeni resursi <br> Vrijeme, energija, računanje) --> Kompromis
Kompromis(Kompromis: 'Dovoljno dobro' rješenje) --> Efikasnost(Efikasno djelovanje)