graph TD
subgraph Dvojaka narav tehnološkog napretka
A[Tehnološki pokretači] --> B[Ambientna inteligencija];
A --> C[Proaktivna autonomija];
A --> D[Hiperpersonalizacija];
A --> E[Sinergija rojeva];
A --> F[Čovjek-AI simbioza];
B --> B1(Osnaživanje: Fluidno okruženje);
B --> B2(Isključivanje: Digitalna barijera);
C --> C1(Osnaživanje: Delegiranje odluka);
C --> C2(Isključivanje: Gubitak poslova);
D --> D1(Osnaživanje: Personalizirana skrb);
D --> D2(Isključivanje: Algoritamsko prosuđivanje);
E --> E1(Osnaživanje: Suradnička inteligencija);
E --> E2(Isključivanje: Centralizacija moći);
F --> F1(Osnaživanje: Uloga "AI-dirigenta");
F --> F2(Isključivanje: Atrofija vještina);