graph TD
style A fill:#fff,stroke:#333,stroke-width:2px
style B fill:#fff,stroke:#333,stroke-width:2px
style C fill:#fff,stroke:#333,stroke-width:2px
style D fill:#fff,stroke:#333,stroke-width:2px
style E fill:#fff,stroke:#333,stroke-width:2px
subgraph "Procesi preobrazbe od regionalnog prema globalnom"
A[<b>Širenje pismenosti</b><br><i>Tehnologija tiska i uporaba vernakulara</i>] --> B{Stvaranje nove<br>javne sfere i<br>mreže učenjaka};
B --> C[<b>Znanstvena revolucija</b><br><i>Empirizam i novi metodološki okvir</i>];
C --> D[<b>Kulturna revolucija</b><br><i>Prosvjetiteljstvo i novi društveni modeli</i>];
end
subgraph "Posljedice"
D --> E[<b>Globalni doseg</b><br><i>Širenje ideja i univerzalizacija znanja</i>];