graph TD
subgraph Faza generiranja
direction LR
A[Obogaćeni odzivnik] --> B{Veliki jezični model};
B -- Uputa: Temelji odgovor na kontekstu --> B;
B --> C[Sintetizirani odgovor];
end
style A fill:#fff,stroke:#333,stroke-width:1.5px
style B fill:#fff,stroke:#333,stroke-width:1.5px
style C fill:#fff,stroke:#333,stroke-width:1.5px