graph TD
A["Početni općeniti upit<br><i>'povijest dubrovačke književnosti'</i>"] --> B{"Agentova ponuda za<br>preciziranje razdoblja"};
B -->|humanizam i renesansa / kasnije razdoblje| C["Korisnikovo sužavanje<br>na renesansu"];
C --> D["Formuliranje kontekstualiziranog<br>LLM prompta"];