graph TD
subgraph 7.2.4 Transverzalna Primjena
style 7.2.4 fill:#fff,stroke:#fff
A[AI Algoritmi za Personalizaciju] --> B(Elektronička Trgovina);
A --> C(Medijski Sadržaji);
A --> D(Informiranje i Vijesti);
A --> E(Obrazovanje);
A --> F(Zdravstvena Skrb);
style A fill:#e6f2ff,stroke:#333,stroke-width:2px
style B fill:#f9f9f9,stroke:#333,stroke-width:1px
style C fill:#f9f9f9,stroke:#333,stroke-width:1px
style D fill:#f9f9f9,stroke:#333,stroke-width:1px
style E fill:#f9f9f9,stroke:#333,stroke-width:1px
style F fill:#f9f9f9,stroke:#333,stroke-width:1px