graph TD
style Agent fill:#f9f9f9,stroke:#333,stroke-width:2px
style Tehnologija fill:#f9f9f9,stroke:#333,stroke-width:2px
style Svrha fill:#f9f9f9,stroke:#333,stroke-width:2px
style Problem fill:#f9f9f9,stroke:#333,stroke-width:2px
subgraph "Tehnološki proces"
Agent -- Prepoznaje --> Problem
Problem -- Zahtijeva --> Svrha(Ispunjavanje svrhe)
Agent -- Koristi i stvara --> Tehnologija
Tehnologija -- Omogućuje --> Svrha
Svrha -- Usmjerava djelovanje --> Agent