graph TD
style Sigurnost fill:#fff,stroke:#333,stroke-width:2px
style Pouzdanost fill:#fff,stroke:#333,stroke-width:2px
style Zlouporaba fill:#fff,stroke:#333,stroke-width:2px
Pouzdanost -->|Preduvjet je za| Sigurnost
Sigurnost -->|Ugrožena je kroz| Zlouporaba
Zlouporaba -->|Iskorištava nedostatke u| Pouzdanost