graph TD
style A fill:#ffffff,stroke:#333,stroke-width:2px
style B fill:#ffffff,stroke:#333,stroke-width:2px
style C fill:#ffffff,stroke:#333,stroke-width:2px
style D fill:#ffffff,stroke:#333,stroke-width:2px
style E fill:#ffffff,stroke:#333,stroke-width:2px
style F fill:#ffffff,stroke:#333,stroke-width:2px
subgraph "Prikaz: Mreža odnosa pojma 'Pravda'"
A(Pravda) --- B(Poštenje)
A --- C(Jednakost)
A --- D(Zakon)
D --- E(Pravo)
D --- F(Dužnost)
B --- C