graph TD
subgraph Životni ciklus modela
direction LR
A[1. Definiranje problema] --> B(2. Prikupljanje i<br>priprema podataka)
B --> C(3. Razvoj i<br>treniranje modela)
C --> D(4. Vrednovanje modela)
D --> E(5. Implementacija)
E --> F(6. Nadzor i<br>održavanje)
F -- Povratna veza --> B
end
style A fill:#f9f9f9,stroke:#333,stroke-width:2px
style B fill:#f9f9f9,stroke:#333,stroke-width:2px
style C fill:#f9f9f9,stroke:#333,stroke-width:2px
style D fill:#f9f9f9,stroke:#333,stroke-width:2px
style E fill:#f9f9f9,stroke:#333,stroke-width:2px
style F fill:#f9f9f9,stroke:#333,stroke-width:2px