graph TD
style A fill:#fff,stroke:#333,stroke-width:2px
style B fill:#fff,stroke:#333,stroke-width:2px
style C fill:#fff,stroke:#333,stroke-width:2px
style D fill:#fff,stroke:#333,stroke-width:2px
style E fill:#fff,stroke:#333,stroke-width:2px
style F fill:#fff,stroke:#333,stroke-width:2px
A(Izum tiskarskog stroja <br><i>Johannes Gutenberg, o. 1440.</i>) --> B(Masovna proizvodnja <br> pisanih materijala)
B --> C(Povećana dostupnost <br> i niža cijena knjiga)
C --> D(Širenje pismenosti i ideja <br><i>Humanizam, Renesansa, Reformacija</i>)
D --> E(Standardizacija jezika <br> i stvaranje nacionalnih kultura)
D --> F(Nastanak javne sfere <br> i javnog mnijenja)