%%{ init: { 'theme': 'base', 'themeVariables': { 'background': 'white', 'primaryColor': '#333', 'nodeBorder': '#333', 'lineColor': '#555', 'textColor': '#222' } } }%%
graph TD
subgraph Polazište
A[Agent / Fenomen]
end
subgraph Odrednice
B(Inherentna svojstva)
C(Kontekstualni čimbenici)
D(Mehanizmi širenja)
end
subgraph Proces
E[Domet<br/><i>(Teorijski potencijal)</i>]
F[Doseg<br/><i>(Stvarno širenje)</i>]
end
subgraph Ishod
G{Utjecaj<br/><i>(Transformacijski, stabilizacijski,<br/>izravni, neizravni)</i>}
end
A --> B
A --> C
B & C --> E
E -- Posredovano s D --> F
F --> G