graph TD
A[Civilizacija: Sumer] --> B(Materijal: Glinene pločice);
B --> C{Oblik zapisa: Klinasto pismo};
C --> D[Primarna funkcija: Administracija i trgovina];
style A fill:#fff,stroke:#333,stroke-width:2px
style B fill:#fff,stroke:#333,stroke-width:2px
style C fill:#fff,stroke:#333,stroke-width:2px
style D fill:#fff,stroke:#333,stroke-width:2px