graph TD
style A fill:#fff,stroke:#333,stroke-width:2px
style B fill:#fff,stroke:#333,stroke-width:2px
style C fill:#fff,stroke:#333,stroke-width:2px
style D fill:#fff,stroke:#333,stroke-width:2px
A[Izvor audio sadržaja <br><i>npr. glas, glazba</i>] --> B{Modulacija <br><i>AM ili FM</i>};
B --> C(Prijenos <br><i>Bežično, brzinom svjetlosti</i>);
C --> D[Prijamnik <br><i>Reprodukcija zvuka</i>];