%%{init: {'theme':'base', 'themeVariables': { 'background': '#ffffff'}}}%%
graph TD
A[Digitalna revolucija] --> B(Interaktivnost i demokratizacija informacija);
B --> C{Velike količine podataka};
C --> D[AI sustavi];
D --> E(Trenutna obrada podataka <br> <i>megabit/s do terabit/s</i>);
E --> F{Globalni doseg i personalizacija};
F --> G[Automatizacija, prilagodba i napredno razumijevanje jezika];