graph TD
subgraph "Shema utemeljenog i provjerljivog odgovora"
style "Shema utemeljenog i provjerljivog odgovora" fill:#fff,stroke:#ddd
A["Izvor<br>Financijsko izvješće Q4 2023"] -- Dohvaća podatke --> B{Agent};
B -- Generira odgovor --> C["Odgovor<br>Prihod tvrtke Inovatek d.o.o. iznosio je 1,2 milijuna eura.<br><i>[Izvor: Financijsko izvješće Q4 2023]</i>"];