graph TD
style AGI fill:#fff,stroke:#333,stroke-width:2px
style Simbolicki fill:#fff,stroke:#333,stroke-width:2px
style Konekcionisticki fill:#fff,stroke:#333,stroke-width:2px
style Hibridni fill:#fff,stroke:#333,stroke-width:2px
style Razvojni fill:#fff,stroke:#333,stroke-width:2px
subgraph "Paradigme istraživanja"
Simbolicki[Simbolički pristup <br><i>(GOFAI)</i>]
Konekcionisticki[Konekcionistički pristup <br><i>(Neuronske mreže)</i>]
Hibridni[Hibridni pristup <br><i>(Sinteza simboličkog i konekcionističkog)</i>]
Razvojni[Razvojni pristup <br><i>(Utjelovljena kognicija)</i>]
end
Simbolicki --> AGI[Umjetna opća inteligencija (AGI)]
Konekcionisticki --> AGI
Hibridni --> AGI
Razvojni --> AGI