graph TD
%%{init: {'theme': 'base', 'themeVariables': { 'background': 'white', 'primaryColor': 'white', 'nodeBorder': 'black', 'lineColor': 'black', 'textColor': 'black'}}}%%
subgraph Model sposobnosti (Mayer & Salovey, 1997)
A(Percepcija emocija) --> B(Uporaba emocija) --> C(Razumijevanje emocija) --> D(Upravljanje emocijama)