graph TD
subgraph "Struktura usmene epohe"
style A fill:#ffffff,stroke:#333,stroke-width:2px
style B fill:#ffffff,stroke:#333,stroke-width:2px
style C fill:#ffffff,stroke:#333,stroke-width:2px
style D fill:#ffffff,stroke:#333,stroke-width:2px
A[<b>Temeljni mediji:</b><br/>Ljudski glas i pamćenje] --> B{<b>Društvene i spoznajne posljedice</b>}
B --> C(Stvaranje malih,<br/>kohezivnih zajednica)
B --> D(Znanje kao osobno<br/>i fluidno iskustvo)
C & D --> E(<b>Kulturni izričaji:</b><br/>Mitski epovi, genealogije,<br/>usmena predaja)