%%{init: {'theme': 'base', 'themeVariables': { 'background': '#ffffff'}}}%%
graph TD
subgraph "Proces demokratizacije znanja putem tiska"
direction LR
A[Razvoj tiskarstva] --> B{Smanjenje troškova <br> i vremena proizvodnje};
B --> C[Masovna dostupnost <br> tiskanih tekstova];
C --> D[Brža razmjena, provjera <br> i nadopuna ideja];
C --> E[Transformacija sveučilišta];
D --> F[Stvaranje isprepletene <br> znanstvene mreže];
E --> G[Uspostava arhiva, knjižnica <br> i znanstvenih časopisa];
F & G --> H[Demokratizacija znanja];