graph TD
subgraph " "
direction LR
A[Usmena predaja] --> B(Pismo i rukopisi);
B --> C{Tiskarski stroj};
C --> D[Digitalno doba i AI agenti];
end
style B fill:#fff,stroke:#333,stroke-width:2px
style C fill:#fff,stroke:#333,stroke-width:2px
style D fill:#fff,stroke:#333,stroke-width:2px
style A fill:#fff,stroke:#333,stroke-width:2px