graph TD
style A fill:#fff,stroke:#333,stroke-width:2px
style B fill:#fff,stroke:#333,stroke-width:2px
style C fill:#fff,stroke:#333,stroke-width:2px
A[Komunikacija] --> B[Društvena organizacija i kultura];
B --> C[Civilizacija];