graph TD
style A fill:#ffffff,stroke:#333,stroke-width:2px
style B fill:#ffffff,stroke:#333,stroke-width:2px
style C fill:#ffffff,stroke:#333,stroke-width:2px
style D fill:#ffffff,stroke:#333,stroke-width:2px
A(Promišljanje) --> B(Snovanje)
B --> C(Djelovanje)
C --> D(Učenje)
D --> A