graph TD
style A fill:#ffffff,stroke:#333,stroke-width:2px
style B fill:#ffffff,stroke:#333,stroke-width:1px
style C fill:#ffffff,stroke:#333,stroke-width:1px
style D fill:#ffffff,stroke:#333,stroke-width:1px
style E fill:#ffffff,stroke:#333,stroke-width:1px
A[Usmene predaje] --> B(Prijenos znanja i pamćenja)
A --> C(Društvena integracija i identitet)
A --> D(Legitimacija poretka i kontrola)
A --> E(Estetska i zabavna funkcija)