%%{init: {'theme': 'base', 'themeVariables': { 'background': '#ffffff'}}}%%
graph TD
A[<b>Prva revolucija</b><br><i>Usmenost</i>] --> B[<b>Druga revolucija</b><br><i>Pismo</i>];
B --> C[<b>Treća revolucija</b><br><i>Tisak</i>];
C --> D[<b>Četvrta revolucija</b><br><i>Digitalno doba</i>];
style A fill:#f9f9f9,stroke:#333,stroke-width:2px
style B fill:#f9f9f9,stroke:#333,stroke-width:2px
style C fill:#f9f9f9,stroke:#333,stroke-width:2px
style D fill:#f9f9f9,stroke:#333,stroke-width:2px